name: ci
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ toJson(steps.gen_output.outputs) }}
    strategy:
      matrix:
        version: [1, 2, 3]
    steps:
      - name: Generate output
        id: gen_output
        run: |
          name='{"name":"Joe"}'
          echo "output_${{ matrix.version }}=${name}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      # Will show
      # {
      #   "output_1": "1",
      #   "output_2": "2",
      #   "output_3": "3"
      # }
      - run: echo '${{ toJSON(needs.job1.outputs) }}'
